[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
phf = { version = "0.11", features = ["macros"] }
counter = "0.6.0"
nalgebra = "0.33.2"
itertools = "0.13.0"
graph_builder = "0.4.1"
